### ISSUE TITLE
Question regarding the results

### ISSUE THREAD

**Issue by atticus-sullivan** [jjccmm/AYTO-Strategies#1]
First of all, nice work. Also on first sight, the code is quite an easy read 👍
(tbh I wanted to implement some heuristics myself, but as far as I thought about it, you have implemented it already so probably I'll just skip implementing it myself)

I just have one question regarding the resulting plots you show (https://github.com/jjccmm/AYTO-Strategies/blob/main/ayto_solver_evaluation.png). How is is possible no solves gets 10 lights (bottom row, second plot) but still they win (top row, 4th plot)?

May this be an artifact from the simulation terminating after solving the riddle without playing the final rounds (with 10 lights constantly)?

Or another idea: (I didn't look in too much detail at the code, I just looked at what the solves are doing)) does *solved run* only mean the riddle is solved after the 10th Matchingnight, in which case the participants still would have lost the whole game as they did not have time to "log in" the solution.

---

Also one small comment, maybe put a note about what *Event Number* refers to in the plots in the *Readme* somewhere.

**Comment by jjccmm** [comment]
Thanks 🙂

Your assumption is correct. If a solver finds the 10 perfect matches in a matching night, the run is solved and terminated, i.e., the following events will not be played. 10 lights can therefore occur for each run only once, and as this is spread over the different weeks in which this is achieved, the mean lights over all runs (which is the plot you mentioned) never reach 10.

A run is solved if the perfect matches are logged in during one of the 10 matching nights. So, if the seating in the 10th night was wrong but provides the information to identify the 10 perfect matches, the run is not considered solved.

I will add a note to the Event Numbers in the Readme

**Comment by atticus-sullivan** [comment]
But then still doesn't that 2nd plot in the bottom row show no strategy achieves 10 lights even after 20 events? Or is this just because the each line represents the mean and the shaded area is something like the standard-deviation (and explicitly not some min/max thing)?
Then this might be a bit confusing as well, but adding a proper explanation might be challenging.

**Comment by jjccmm** [comment]
Yes, the line represents the mean, and the shaded area represents the standard deviation. If the shaded area showed the min-max range, the whole plot would be shaded.

This is, of course, just a basic analysis, and one could dive deeper into all these metrics to gain more insights. For me, the interesting part was (1) how good you can get and (2) what factor "love" plays.

**Comment by atticus-sullivan** [comment]
Ah I see. Then I was just missing the standard deviation part 👍.

I don't think I'd have done more regarding the analysis, probably you've already done more. Tbh I always was only interested in (1) 😅 So I really was interested in how computationally feasible it is, calculating the "real" optimum for the matchingnight (matchbox is easy of course), like you're doing in
https://github.com/jjccmm/AYTO-Strategies/blob/b87d52030041017dc72f6b9f504d979444b3b399/ayto_solver.py#L150
https://github.com/jjccmm/AYTO-Strategies/blob/b87d52030041017dc72f6b9f504d979444b3b399/ayto_solver.py#L169-L172
Btw if you're aiming for performance you can probably "hardcode" something for MN#1 since there are only two scenarios at that point: MB#1 was a match or not.

I also though about some *hybrid* approaches like doing the (real) optimum only later, and do something like:
1. last MN gives you 3 lights
2. keep 3 (random) matches
3. select others random
in the beginning (especially for MN#2) where computing the (real) optimum is computationally infeasible.
In the hope this lets you learn more. But it was just observation that this worked in the beginning (at least sometimes, I didn't do a deep research here) and more a gut feeling.

But as I said having some results already, I don't think I'll continue in this direction codewise for now.

**Comment by jjccmm** [comment]
For the first three matching nights, it's not hardcoded but it just takes 50 random options and selects the best of them. My finding was that even if I spend a lot of time searching in the first matching nights, there is no significant improvement over just using random selection.

Your idea was also on my list, as I thought this could be a good strategy that could actually be done in the show or on paper. But I underestimated how hard it is to find valid solutions that fulfill all the constraints we have, even when doing it on paper. This always led to the point where, in the end, you have to fill up with matches that you are sure are not perfect matches.

So, the real challenge is to find a valid seating arrangement. If you then add the additional constraint that you only want to change X random seatings, it becomes even harder. Of course, it's possible—but not practical.

**Comment by atticus-sullivan** [comment]
Hm, I see. Maybe I underestimate how far you have to go (but just looked it up after MB#4 in season 6 it was just something like 7.3k which should be feasible I think) until computing the optimum becomes feasible. Because in my mind this idea was really only for the second, maybe third matching-night (so for me this approach was never something for the end where you have lots of constraints to fulfill).

Also another thing maybe to consider (not making this process harder): Are we sure the matching in a matchingnight has to fulfill all constraints to get the maximum information? Can't it be that placing a known no-match may get you more information 🤔

**Comment by jjccmm** [comment]
Yeah its sure feasible but not as a "paper method".

Interesting idea with the no-match in the seating... Its against my intuition but i have no proof. It could be brute forced with maybe 5/5 participants to see if a counterexamples can be found. 

Another open point: All solvers here are greedy, i.e. they only maximize the reward for the next step. It could be that a solver that accepts a suboptimal reward in step n can generate a bigger reward in step n+i that otherwise would not have been possible.


But for me this analysis is done and i will spend my time on other projects ;)

**Comment by atticus-sullivan** [comment]
> Interesting idea with the no-match in the seating... Its against my intuition but i have no proof. It could be brute forced with maybe 5/5 participants to see if a counterexamples can be found.

Maybe I'll think about this one, but I don't think I'll do more

> Another open point: All solvers here are greedy, i.e. they only maximize the reward for the next step. It could be that a solver that accepts a suboptimal reward in step n can generate a bigger reward in step n+i that otherwise would not have been possible.

This very much develops into the direction of using something like machine learning (not necessarily but probably deep learning) ^^

> But for me this analysis is done and i will spend my time on other projects ;)

👍 Then thanks for the nice discussion and have fun coding (or what your projects are)
